[project]
name = "robot"
version = "0.1.0"
description = "YAM-Robot imitation learning pipeline"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "i2rt @ git+https://github.com/i2rt-robotics/i2rt.git@5b72c47239bd056d0fa6c1a39edeb0537c89443c",
    "mink==1.1.0",
    "mujoco==3.12",
    "numpy==2.2.6",
    "mjviser>=0.0.14",
    "pynput>=1.8.2",
    "pyspacemouse>=2.1.0",
    "viser>=1.0.30",
    "rust-just>=1.58.0",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8",
    "pybind11-stubgen>=2.5.5",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "ruff>=0.16.5",
]


[tool.basedpyright]
reportUnknownMemberType = "none"

[tool.ty]
environment.extra-paths = ["typings"]

[tool.ruff]
lint.extend-select = ["C901"]
lint.mccabe.max-complexity = 8

[tool.uv]
build-constraint-dependencies = ["scikit-build-core<0.10"]
